services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false


    ### API
    App\Catalog\API\REST\MovieController: ~


    ### Application
    App\Catalog\Application\Command\Handler\:
        resource: '../../src/Catalog/Application/Command/Handler/*'

    App\Catalog\Application\Query\Handler\:
        resource: '../../src/Catalog/Application/Query/Handler/*'

    App\Catalog\Application\Ports\MovieReadModel: '@App\Catalog\Infrastructure\DbalMovieReadModel'


    ### Domain:
    App\Catalog\Domain\Ports\MovieRepository: '@App\Catalog\Infrastructure\DbalMovieRepository'


    ### Infrastructure
    App\Catalog\Infrastructure\DbalMovieReadModel: ~
    App\Catalog\Infrastructure\DbalMovieRepository: ~
