services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false


    ### Interfaces
    App\Facilities\Interfaces\Controllers\:
        resource: '../../src/Facilities/Interfaces/Controllers/*'


    ### Application
    App\Facilities\Application\Services\:
        resource: '../../src/Facilities/Application/Services/*'
        public: true

    App\Facilities\Application\Ports\HallReadModel: '@App\Facilities\Infrastructure\DbalHallReadModel'
    App\Facilities\Application\Ports\ReservationReadModel: '@App\Facilities\Infrastructure\DbalReservationReadModel'


    ### Domain:
    App\Facilities\Domain\Services\:
        resource: '../../src/Facilities/Domain/Services/*'
        public: true

    App\Facilities\Domain\Ports\HallRepository: '@App\Facilities\Infrastructure\DbalHallRepository'
    App\Facilities\Domain\Ports\ReservationRepository: '@App\Facilities\Infrastructure\DbalReservationRepository'
    App\Facilities\Domain\Ports\CalendarRepository: '@App\Facilities\Infrastructure\DbalCalendarRepository'


    ### Infrastructure
    App\Facilities\Infrastructure\:
        resource: '../../src/Facilities/Infrastructure/*'
