services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false


    ### Interfaces
    App\Facilities\Interfaces\Controllers\:
        resource: '../../src/Facilities/Interfaces/Controllers/*'


    ### Application
    App\Facilities\Application\Command\Handler\:
        resource: '../../src/Facilities/Application/Command/Handler/*'

    App\Facilities\Application\Query\Handler\:
        resource: '../../src/Facilities/Application/Query/Handler/*'

    App\Facilities\Application\Ports\HallReadModel: '@App\Facilities\Infrastructure\DbalHallReadModel'


    ### Domain:
    App\Facilities\Domain\Ports\HallRepository: '@App\Facilities\Infrastructure\DbalHallRepository'


    ### Infrastructure
    App\Facilities\Infrastructure\:
        resource: '../../src/Facilities/Infrastructure/*'
