# Read the documentation at https://github.com/thephpleague/flysystem-bundle/blob/master/docs/1-getting-started.md
flysystem:
    storages:
        default.storage:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/var/storage/default'
        cdn:
            adapter: 'app.flysystem.s3_adapter'

when@test:
    flysystem:
        storages:
            cdn:
                adapter: 'app.flysystem.memory_adapter'
