security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
            algorithm: sha256
            encode_as_base64: false
            iterations: 1

    providers:
        admin:
            memory:
                users:
                    admin:
                        password: '%env(ADMIN_PASSWORD)%'
                        roles: ['ROLE_ADMIN']

    firewalls:
        dev:
            pattern: ^/(_profiler|_wdt|assets|build)/
            security: false
        admin:
            pattern: ^/admin
            provider: admin
            stateless: true
            http_basic:
                realm: Secured Area
    access_control:
        - { path: ^/admin, roles: [IS_AUTHENTICATED_FULLY, ROLE_ADMIN] }
