parameters:
    app: 'symfony-cinema'


imports:
    - { resource: services/core.yaml }
    - { resource: services/catalog.yaml }
    - { resource: services/facilities.yaml }
    - { resource: services/planning.yaml }

services:
    _defaults:
        autowire: true
        autoconfigure: true
